apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-healthcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-healthcare
  template:
    metadata:
      labels:
        app: devsecops-healthcare
    spec:
      containers:
      - name: healthcare-container
        image: vidhi4941/devsecops-healthcare:latest
        ports:
        - containerPort: 3002
