apiVersion: v1
kind: Service
metadata:
  name: devsecops-healthcare-service
spec:
  selector:
    app: devsecops-healthcare
  type: NodePort
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30010
