apiVersion: v1
kind: Service
metadata:
  name: devsecops-service
spec:
  selector:
    app: devsecops-app
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 30009
  type: NodePort
